[main]
include=~/.config/foot/colors
gamma-correct-blending=no 

#font=MesloLGS NF:size=10
font=MesloLGS NF:size=10
pad=10x10

[scrollback]
indicator-format=line
lines=10000

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
