source = $HOME/.config/hypr/colors.conf

$accent = $blue
$accentAlpha = $blueAlpha
$font = Noto Sans Bold

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.local/share/backgrounds/static_space_1.png
  blur_passes = 0
  color = $base
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 80
  font_family = $font
  position = 0, 240
  halign = center
  valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 18
  font_family = $font
  position = 0, 160
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 180, 40
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾  Sesión iniciada con </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -225
  halign = center
  valign = center
}z
