gui:
  theme:
    activeBorderColor:
      - '#9d7cd8'
      - bold
    inactiveBorderColor:
      - '#414868'
    optionsTextColor:
      - '#7dcfff'
    selectedLineBgColor:
      - '#1f2335'
    cherryPickedCommitBgColor:
      - '#24283b'
    cherryPickedCommitFgColor:
      - '#7aa2f7'
    unstagedChangesColor:
      - '#f7768e'
    defaultFgColor:
      - '#c0caf5'
    searchingActiveBorderColor:
      - '#e0af68'

  authorColors:
    '*': '#bb9af7'
