set viewmode miller

set show_hidden false

set confirm_on_delete multiple

set confirm_on_trash always

#set use_preview_script true
#set preview_script ~/.config/ranger/scope.sh

set automatically_count_files true

set preview_images true
set preview_images_method w3m
