$blue = rgb(81a1c1)
$blueAlpha = 81a1c1

$red = rgb(bf616a)
$redAlpha = bf616a

$yellow = rgb(ebcb8b)
$yellowAlpha = ebcb8b

$text = rgb(d8dee9)
$textAlpha = d8dee9

$overlay0 = rgb(616d85)
$overlay0Alpha = 616d85

$surface0 = rgb(313244)
$surface0Alpha = 313244

$base = rgb(242932)
$baseAlpha = 242932
